#ifndef FACTORY_FACTORY_CONFIG_H_
#define FACTORY_FACTORY_CONFIG_H_

#include "Project_cfg.h"

// 默认使用STM32平台
#ifndef TARGET_PLATFORM
#define TARGET_PLATFORM PLATFORM_STM32
#endif

/* 各个驱动模块的平台选择配置 */
#if (TARGET_PLATFORM == PLATFORM_STM32)
#define GPIO_DRIVER_PLATFORM 	PLATFORM_STM32
#define PWM_DRIVER_PLATFORM 	PLATFORM_STM32
#define USART_DRIVER_PLATFORM 	PLATFORM_STM32
#define SDRAM_DRIVER_PLATFORM 	PLATFORM_STM32
#else
#error "factory_config: 未定义有效的目标平台，请检查TARGET_PLATFORM配置"
#endif

#endif /* FACTORY_FACTORY_CONFIG_H_ */
